/**
 * Placeholder app class generated by template tooling.
 */
public class App {

    /**
     * Prints a simple message.
     *
     * @param args command-line arguments (unused)
     * @throws Exception if an error occurs
     */
    public static void main(String[] args) throws Exception {
        System.out.println("Hello, World!");
    }
}
